### ISSUE TITLE
Incorrect behaviour

### ISSUE THREAD

**Issue by xepozz** [yiisoft/translator-extractor#8]
[Extractor](https://github.com/yiisoft/translator-extractor/blob/master/src/Extractor.php#L16) gets MessageWriteInterface and MessageReadInterface, but they are available only in `CategoryMessage` context.
Whole application can have multiple messages sources, using only one of them is incorrect.

**Comment by samdark** [comment]
Do you mean you want to be able to write extracted messages into multiple sources at once?

**Comment by xepozz** [comment]
Not really. I would say to have writer or reader as a service is wrong design. They are needed only for polymorphism now.

This extractor should work by the following rules:
1. Gets path where it will find messages
2. Category (messages domain) that it will append.

For example:
`./yii extract views/module1 module1` it will search any new messages from the directory `views/module1/*` and will append to translations file `resources/messages/en/module1.php`, if that file configured for `module1` category.

**Comment by samdark** [comment]
Well, it does more than that:

1. It reads all the messages from the source code.
2. It reads all the message translations from message source (it may be DB or something else, not necessary files).
3. It checks if all the current message translations have corresponding messages in the message source. If not, it may either make these translations as deprecated or remove them.
4. It checks if all the message from the source code have translations in the message source. If not, an empty translation is added.

These actions are time-tested with Yii 2. The approach worked really well.

**Comment by xepozz** [comment]
> It checks if all the message from the source code have translations in the message source.

Yes, but it should check all sources, but only "main".
